INSERT INTO HOTEL (HOTEL_ID,DOUBLE_BED_ROOM_PRICE,HOTEL_NAME,SINGE_BED_ROOM_PRICE,THREE_BED_ROOM_PRICE) values (1000,4000,'MERIDIEN',2000,6000);

INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (101,'SINGLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (102,'SINGLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (103,'SINGLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (104,'SINGLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (105,'SINGLE_BED',1000);

INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (201,'DOUBLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (202,'DOUBLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (203,'DOUBLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (204,'DOUBLE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (205,'DOUBLE_BED',1000);


INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (301,'THREE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (302,'THREE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (303,'THREE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (304,'THREE_BED',1000);
INSERT INTO ROOM (ROOM_NUM,ROOM_TYPE,HOTEL_ID) values (305,'THREE_BED',1000);

INSERT INTO USER(ID,ADDRESS,CONTACT_NUMBER,FIRST_NAME,LAST_NAME,USER_TYPE) values (1000,'BENGALURU','8951238982','HOTEL','ADMIN','ADMIN');
INSERT INTO USER(ID,ADDRESS,CONTACT_NUMBER,FIRST_NAME,LAST_NAME,USER_TYPE) values (2000,'BENGALURU','8951238982','Shruthi','Naik','USER');


